export default function Head() {
  return (
    <>
      <title>Dev Funny</title>
      {/* <meta name="description" content="Generated by create next app" /> */}
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
